INSERT INTO wati.tb_tip
(title,description,week,day)
VALUES
('Dica 1', 'A fissura dura em média de 2 a 5 minutos. Nesses momentos beba um copo de água ou escove os dentes.', '1', '0'),
('Dica 2', 'Escovar os dentes após comer ou beber algo que você associa ao cigarro pode diminuir sua vontade de fumar.', '1', '0'),
('Dica 3', 'Quando sentir vontade de acender um cigarro coma alimentos de baixo de teor calórico como por exemplo, frutas, cenouras, salsão, pepino, etc.', '1', '0'),
('Dica 4', 'Durante o processo de cessação é comum ocorrer episódios de recaída, mas não desanime, continue firme no seu propósito de parar de fumar.', '3', '0'),
('Dica 5', 'Comer frutas ou alimentos de baixas calorias ajudam nos momentos de fissura e a não ganhar peso.', '2', '0'),
('Dica 6', 'Parar de fumar aumenta a expectativa e a qualidade de vida.', '4', '0'),
('Dica 7', 'Tenha sempre perto de você garrafas de água e quando tiver vontade de fumar tome alguns goles da água.', '3', '0'),
('Dica 8', 'Ao parar de fumar você se sentirá melhor fisicamente e terá mais disposição para realizar exercícios físicos.', '4', '0'),
('Dica 9', 'Ao deixar de fumar você reduz as chances de desenvolver doenças do coração, doenças pulmonares e cânceres.', '2', '0'),
('Dica 10', 'Se além de você existe outro fumante em casa, peça para que ele evite fumar perto de você e proponha a essa pessoa uma tentativa de parar. Um poderá dar suporte ao outro.', '1', '0'),
('Dica 11', 'Guarde o dinheiro que você gasta com cigarros e ao final de um ano você poderá investir algo prazeroso, como uma viagem, por exemplo.', '3', '0'),

('Dica 12', 'Evite comidas ou bebidas que você associa ao cigarro, como por exemplo, café, álcool, doces, etc.', '1', '0'),
('Dica 13', 'Pense nas suas atividades diárias e em que momento você tem vontade de fumar e procure mudar esse comportamento.', '2', '0'),
('Dica 14', 'Participar de grupos de apoio para fumantes/ex-fumantes podem aumentar suas chances de parar de fumar.', '1', '0'),
('Dica 15', 'Em 15 anos após parar,  os riscos de sofrer de doenças cardiacas são iguais a de uma pessoa que nunca fumou.', '4', '0'),
('Dica 16', 'Não desista diante das recaídas. A maioria das pessoas que conseguem deixar de fumar não conseguem da primeira vez.', '4', '0'),
('Dica 17', 'Comunique seus familiares e amigos próximos sobre seu processo de parar de fumar e peça a compreensão deles durante esse período.', '1', '0'),
('Dica 18', 'Identifique as situações que te levam a fumar e procure evitá-las.', '2', '0'),
('Dica 19', 'Ao invés de acender um cigarro quando você estiver estressado, respire profundamente durante alguns minutos e tente relaxar.', '3', '0'),
('Dica 20', 'Procure o apoio de sua família e amigos se você estiver precisando desabafar.', '4', '0'),
('Dica 21', 'Evite frequentar ambientes onde todos fumam para não despertar o desejo de acender um cigarro.', '3', '0'),
('Dica 22', 'A prática de exercícios físicos pode ajudar a diminuir a ansiedade e evitar o ganho de peso.', '1', '0'),
('Dica 23', 'Procure evita situações estressantes durante o processo de parar de fumar.', '2', '0'),
('Dica 24', 'Beba bastante água durante o dia para ajudar na desintoxicação da nicotina.', '2', '0'),
('Dica 25', 'Tente mudar sua rotina para evitar situações associadas ao hábito de fumar.', '3', '0'),
('Dica 26', 'Faça uma lista de razões pelas quais é importante você parar de fumar.', '2', '0'),
('Dica 27', 'Procure o apoio de grupos de pessoas que também estão tentando parar de fumar. Há grupos de ajuda na internet, inclusive Facebook', '4', '0'),
('Dica 28', 'Evite comportamentos ou situações que reforcem o desejo de acender um cigarro.', '3', '0')



('Dica 29', 'Você está há 1 dia sem fumar. E hoje você já deixou de inalar mais de 4.700 substâncias tóxicas, tais como a amônia. monóxido de carbono, acetona e alcatrão.', '1', '1'),
('Dica 30', 'Você está há 2 dias sem fumar. Sua pressão sanguínea e pulsação estão iguais a de um não fumante.', '1', '2'),
('Dica 30', 'Você está há 3 dias sem fumar e seu olfato e paladar já começaram a ganhar sensibilidade novamente.', '1', '3'),
('Dica 31', 'No 4ª dia sem fumar o nível de oxigênio no seu sangue se normaliza e você não tem mais nicotina circulando no seu sangue.', '1', '4'),
('Dica 32', 'Em 5 dias sem fumar seus brônquios estão funcionando melhor e estão limpando os resíduos deixados pelo pelo fumo nas vias respiratórias.', '1', '5'),
('Dica 33', 'Nesses primeiros dias sem cigarros a vontade fumar é maior, procure frequentar lugares onde uso do cigarro é proibido como cinemas, teatros, shoppings por exemplo.', '1', '6'),
('Dica 34', 'Parabéns! Você está há 7 dias sem fumar. Sua pele e cabelo já devem estar melhores.', '1', '7'),
('Dica 35', 'Você está há 8 dias sem fumar e você pode estar se sentindo um pouco irritado. Por isso tente fazer exercicios de relaxamento ou fazer algo que lhe traga bem-estar.', '2', '8'),
('Dica 36', 'Você está há 9 dias sem fumar. Sua boca e pele não tem mais aquele cheiro forte produzido pelo cigarro.', '2', '9'),
('Dica 37', 'Nas primeiras semanas sem fumar você pode se sentir muito ansioso ou nervoso. Nesses momentos fique de pé, feche os olhos e respire lenta e profundamente. Isso ajudará a se relaxar.', '2', '10'),
('Dica 38', 'Você está há 11 dias sem acender um cigarro.Procure realizar alguma atividade física. Ninguém sente vontade de fumar enquanto corre, anda de bicicleta ou nada.', '2', '11'),
('Dica 39', 'No 12ª dia sem fumar o forte desejo de fumar vai se tornando mais brando.', '2', '12'),
('Dica 40', 'Em quase 2 semanas sem cigarros você se cansará menos ao fazer exercícios físicos.', '2', '13'),
('Dica 40', 'Parabéns!! Você está há 2 semanas sem fumar. Mantenha-se confiante no seu propósito de parar de fumar. Acredite em você!', '2', '14'),
('Dica 41', 'Em 15 dias sem fumar sua respiração fica mais fácil e você se sente mais disposto para realizar suas atividades.', '3', '15'),
('Dica 42', 'Após 2 semanas seu apetite vai melhorar, seus sentidos de gostos e olfato também. Os alimentos terão melhor sabor e aroma.', '3', '16'),
('Dica 43', 'Em quase 3 semanas tente fazer um planejamento futuro e procure imaginar sua vida sem o cigarro e quais os benefícios isso trará para você.', '3', '18'),
('Dica 44', 'Você está há 19 dias sem fumar. Foque sua atenção em coisas que não estejam relacionadas ao desejo de fumar.','3','19'),
('Dica 45', 'Faça o cálculo do quanto de dinheiro você já economizou em quase 3 semanas sem fumar.', '3','20'),
('Dica 46', 'Parabéns!! Você está há 3 semanas sem fumar. Resista ao desejo de acender um cigarro! A vontade passa tão rápida quanto chega.', '3', '21')